services:
  php-web:
    build:
      context: ./php
    container_name: php-web
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
      - ./php/data.db:/var/www/html/data.db
    depends_on:
      - mongodb
      - neo4j
      - mosquitto
      - mysql  

  subscriber:
    build:
      context: ./subscriber
    container_name: mqtt-subscriber
    depends_on:
      - mongodb
      - neo4j
      - mosquitto
      - mysql 
    volumes:
      - ./php/data.db:/app/data.db 
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test1234

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped  

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/test1234"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  mysql:  
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: iot_data
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mongodb_data:
  neo4j_data:
  neo4j_logs:
  mysql_data:  